// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzvzyogpqvumqerbgtdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6dnp5b2dwcXZ1bXFlcmJndGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjEzNjQsImV4cCI6MjA2NTMzNzM2NH0.ROcDSrhtTqY0x2GNz9-zAsGlpoS9pNaRerXlx1BB1E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);